# Generated by Django 5.0.6 on 2025-05-02 11:09

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True # Although empty, it's the first in the app

    dependencies = [
        # Add dependencies if this migration depends on others
        # e.g., ('other_app', '0001_initial'),
    ]

    operations = [
        VectorExtension(), # Add this line to enable the extension
    ]
